
import Sidebar from "@/components/Sidebar";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-full flex relative  scrollbar-none">
        <Sidebar />
        <div className="w-full  p-3  overflow-x-hidden">{children}</div>
      </body>
    </html>
  );
}
